version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: qassemi
      POSTGRES_PASSWORD: qassemi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: qassemi@qassemi.com
      PGADMIN_DEFAULT_PASSWORD: qassemi
    ports:
      - "8080:80"
    networks:
      - dev-network

  vscode:
    image: codercom/code-server:latest
    environment:
      PASSWORD: "qassemi"
    volumes:
      - ./workspace:/home/coder/project
    ports:
      - "8443:8443"
    networks:
      - dev-network

  java:
    image: openjdk:latest
    volumes:
      - ./java-app:/usr/src/app
    networks:
      - dev-network
    command: ["sh", "-c", "while :; do sleep 2073600; done"]

  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "8081:80"
    volumes:
      - ./filebrowser/config:/config
      - ./filebrowser/files:/srv
    networks:
      - dev-network

networks:
  dev-network:

volumes:
  postgres_data:
